DEBUG = False
IMG_ROOT = 'static/imgs/'
TIMELIMIT = 600

# status codes
NOT_LOGIN = 'NOT_LOGIN'
GET_SUCCESS = 'GET_SUCCESS'
NAME_PASSWORD_WRONG = 'NAME_PASSWORD_WRONG'
NAME_NULL = 'NAME_NULL'
PASSWORD_NULL = 'PASSWORD_NULL'
LOGIN_EXPIRED = 'LOGIN_EXPIRED'
LOGINOUT_UNKNOWN = 'LOGINOUT_UNKNOWN'
LIMIT_EXCEEDED = 'LIMIT_EXCEEDED'

LIKE_SUCCESS = 'LIKE_SUCCESS'
LIKE_FAILED = 'LIKE_FAILED'

USER_UNEXIST = 'USER_UNEXIST'

PROJ_SUCCESS = 'PROJ_SUCCESS'
TITLE_NULL = 'TITLE_NULL'
PROJ_DELETED = 'PROJ_DELETED'
PROJ_UNEXIST = 'PROJ_UNEXIST'
PROJ_NO_AUTHORIZE = 'PROJ_NO_AUTHORIZE'
PROJ_UNKNOWN = 'PROJ_UNKNOWN'

REQ_SUCCESS = 'REQ_SUCCESS'
REQ_ERROR = 'REQ_ERROR'
REQ_UNKNOWN = 'REQ_UNKNOWN'
REQ_EXIST = 'REQ_EXIST'
REQ_UNEXIST = 'REQ_UNEXIST'

RSP_ERROR = 'RSP_ERROR'
RSP_SUCCESS = 'RSP_SUCCESS'
RSP_UNKNOWN = 'RSP_UNKNOWN'

JOIN_SUCCESS = 'JOIN_SUCCESS'
JOIN_ERROR = 'JOIN_ERROR'
JOIN_UNKNOWN = 'JOIN_UNKNOWN'

INFO_SUCCESS = 'INFO_SUCCESS'
INFO_ERROR = 'INFO_ERROR'
INFO_UNKNOWN = 'INFO_UNKNOWN'

TAG_SUCCESS = 'TAG_SUCCESS'
TAG_FAILED = 'TAG_FAILED'
TAG_UNKNOWN = 'TAG_UNKNOWN'

REPLY_SUCCESS = 'REPLY_SUCCESS'
CONTENT_NULL = 'CONTENT_NULL'
REPLY_DELETED = 'REPLY_DELETED'
REPLY_UNEXIST = 'REPLY_UNEXIST'
REPLY_NO_AUTHORIZE = 'REPLY_NO_AUTHORIZE'
REPLY_UNKNOWN = 'REPLY_UNKNOWN'

MERGE_SUCCESS = 'MERGE_SUCCESS'
MERGE_FAILED = 'MERGE_FAILED'

MESSAGE_SUCCESS = 'MESSAGE_SUCCESS'
MESSAGE_FAILED = 'MESSAGE_FAILED'

NOTICE_SUCCESS = 'NOTICE_SUCCESS'
NOTICE_FAILED = 'NOTICE_FAILED'
NOTICE_NO_AUTHORIZE = 'NOTICE_NO_AUTHORIZE'

SET_SUCCESS = 'SET_SUCCESS'
SET_FAILED = 'SET_FAILED'

IMAGE_NULL = 'IMAGE_NULL'
IMAGE_OVERSIZE = 'IMAGE_OVERSIZE'
IMAGE_SUCCESS = 'IMAGE_SUCCESS'
IMAGE_FAILED = 'IMAGE_FAILED'

SEARCH_SUCCESS = 'SEARCH_SUCCESS'
SEARCH_FAILED = 'SEARCH_FAILED'
SEARCH_EMPTY = 'SEARCH_EMPTY'
